const assert=require('node:assert/strict');
const {match,parse}=require('./jd-match');
const resume=[{title:'工作经历',content:'使用 Excel 整理报名数据。完成用户访谈并汇总用户研究发现。提出 A/B 测试方案。没有 Python 经验。'},{title:'技能与证书',content:'SQL 基础；CET-6'}];
assert.equal(match('熟练 SQL',resume)[0].status,'related');
assert.equal(match('Python 开发',resume)[0].status,'missing');
assert.equal(match('Excel 和 Python',resume)[0].status,'related');
assert.equal(match('Excel 或 Python',resume)[0].status,'evidence');
assert.equal(match('A/B 测试',resume)[0].status,'related');
assert.equal(match('流利英语',resume)[0].status,'missing');
assert.equal(match('本科以上，至少3年经验',resume)[0].status,'review');
assert.equal(match('Java', [{title:'技能与证书',content:'JavaScript'}])[0].status,'missing');
assert.equal(match('用户研究',resume)[0].evidence[0].module,0);
assert.equal(match('SQL、Python',resume)[0].status,'related');
assert.equal(parse('加分项\nSQL 优先')[0].priority,'加分项');
assert.equal(parse('福利待遇\n免费午餐').length,0);
assert.equal(parse('负责一些尚未覆盖的任务')[0].clause,'负责一些尚未覆盖的任务');
assert.equal(match('未知技能要求',resume)[0].status,'review');
assert.equal(match('无需 Python 经验',resume)[0].status,'review');
assert.equal(match('',resume).length,0);
console.log('16 JD evidence checks passed');
