const assert=require('node:assert/strict');
const {classify}=require('./resume-fields.js');
const sample='张三\n手机：13800138000\n示例大学 | 本科 | 2020-2024\n专业：计算机科学\n示例科技有限公司 | 开发实习生\n负责开发报名系统\n\n使用 SQL 整理数据\n校园报名项目\n完成页面设计\n技能：JavaScript、SQL\n语言能力：英语';
const result=classify(sample);
assert.deepEqual(result.map(x=>x.title),['基本信息','教育背景','工作经历','项目经历','技能与证书']);
assert.match(result[2].data.notes,/使用 SQL/);
assert.equal(result[0].data.fields.phone,'13800138000');
assert.equal(result.map(x=>x.content).join('\n'),sample.split('\n').filter(Boolean).join('\n'));
assert.equal(classify('无法确定归属的内容')[0].title,'其他经历');
assert.equal(classify('工作经历\n甲方有限公司\n负责大学客户业务\n乙方有限公司\n参与产品开发').length,2);
assert.equal(classify('教育经历\n示例大学\n\n专业：数学').length,1);
assert.equal(classify('项目经历\n报名系统\n负责开发页面')[0].title,'项目经历');
assert.equal(classify('').length,0);
const interrupted=classify('工作经历\n示例有限公司\n负责数据整理\n邮箱：test@example.com\n完成周报');
assert.equal(interrupted.filter(x=>x.title==='工作经历').length,1);
assert.match(interrupted[0].content,/完成周报/);
assert.equal(classify('教育背景：示例大学')[0].data.fields.school,'示例大学');
assert.equal(classify('\n基本信息\n张三')[0].data.fields.name,'张三');
console.log('13 classification assertions passed');
