const assert=require('node:assert/strict');
const {classify}=require('./resume-fields.js');
const sample='张三\n手机：13800138000\n示例大学 | 本科 | 2020-2024\n专业：计算机科学\n示例科技有限公司 | 开发实习生\n负责开发报名系统\n\n使用 SQL 整理数据\n校园报名项目\n完成页面设计\n技能：JavaScript、SQL\n语言能力：英语';
const result=classify(sample);
assert.deepEqual(result.map(x=>x.title),['基本信息','教育背景','工作经历','项目经历','技能与证书']);
assert.match(result[2].data.notes,/使用 SQL/);
assert.equal(result[0].data.fields.phone,'13800138000');
assert.equal(result.map(x=>x.content).join('\n'),sample.split('\n').filter(Boolean).join('\n'));
assert.equal(classify('无法确定归属的内容')[0].title,'其他经历');
assert.equal(classify('工作经历\n甲方有限公司\n负责大学客户业务\n乙方有限公司\n参与产品开发').length,2);
assert.equal(classify('教育经历\n示例大学\n\n专业：数学').length,1);
assert.equal(classify('项目经历\n报名系统\n负责开发页面')[0].title,'项目经历');
assert.equal(classify('').length,0);
const interrupted=classify('工作经历\n示例有限公司\n负责数据整理\n邮箱：test@example.com\n完成周报');
assert.equal(interrupted.filter(x=>x.title==='工作经历').length,1);
assert.match(interrupted[0].content,/完成周报/);
assert.equal(classify('教育背景：示例大学')[0].data.fields.school,'示例大学');
assert.equal(classify('\n基本信息\n张三')[0].data.fields.name,'张三');
const {pdfText}=require('./resume-fields.js');
const item=(str,x,y,width=30)=>({str,width,transform:[10,0,0,10,x,y]});
assert.equal(pdfText([item('实 习 经 历',0,50),item('邮箱：demo@example.com',0,90),item('姓名：测试',0,100)]),'姓名：测试\n邮箱：demo@example.com\n实 习 经 历');
const layout=classify('实 习 经 历\n2023.06 — 2023.08\t示例律师事务所\t律师助理\n工作概述：\n整理案件\n2024.07 — 2024.08\t示例人民法院（民一庭）\t实习生\n完成检索\n校 园 经 历\n2022.10 — 2024.06\t示例大学社团\t社长\nAI 能 力 与 智 能 体 实 践\nAI Agent 产品设计与开发实践\n· 实现原型\nAI 辅助研究与知识管理\n· 完成研究');
assert.deepEqual(layout.map(x=>x.title),['工作经历','工作经历','校园经历','AI 实践','AI 实践']);
assert.equal(layout[1].data.fields.company,'示例人民法院（民一庭）');
assert.equal(layout[1].data.fields.role,'实习生');
const award=classify('教育背景\n示例大学 本科\n荣誉奖项：研究奖\n优秀志愿者\n实习经历\n示例公司');
assert.match(award.find(x=>x.title==='技能与证书').content,/优秀志愿者/);
console.log('18 classification assertions passed');
